<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <meta charset="utf-8"/>
        <title>Animal Quiz</title>
        <style>
            body {
                margin: 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
                background: url("https://images.vexels.com/media/users/3/157149/raw/5ed9149356d9abecb4713a0dca4fa46b-jungle-background-design.jpg");
                background-position: center center;
                background-repeat: no-repeat;
                background-size: cover;
            }

            .overlay {
                background-color: rgba(116, 116, 116, 0.53);
                height: 100%;
            }

            h1 {
                color: #dddddd;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                margin: 0;
                font-weight: bold;
                text-shadow: 4px 5px #000000;
            }

            form {
                width: 50%;
                margin: 0 auto;
            }

            .card {
                color: #2c2c2c;
            }
        </style>
        <?php session_start(); ?>
    </head>
    <body>
    <div class="overlay">
        <h1>Animal Quiz</h1>
        <form action="results">
            <?php
            $list = '';
            $i = 1;
            foreach ($questions as $question) {
                $list .= '<div class="card bg-light mb-3">
                <div class="card-header">Question ' . $i++ . '</div>
                <div class="card-body">
                    <h5 class="card-title">'
                    . $question->question . '</h5>
                    <select name="'. $question->id . '" class="custom-select" size="4">';
//                $id = ;
                foreach ($question->all_answers as $answer) {
                    $list .= '<option name="' . $id . '" value="' . $answer . '">' . $answer . '</option>';
                }
            $list .= '</select></div></div>';
            }
            echo $list;
            ?>
            <input type="submit" class="btn btn-primary mb-4">
        </form>
    </div>

    </body>
</html>
